document.getElementById('ing_1').onclick = function(){
    document.getElementById('sub_1').innerHTML = "Software Developer"
    document.getElementById('skills').innerHTML = "SKILLS"
    document.getElementById('prog').innerHTML = "Software"
    document.getElementById('agile').innerHTML = "Agile - SCRUM"
    document.getElementById('elec').innerHTML = "Electronics"
    document.getElementById('comp').innerHTML = "Computing"
    document.getElementById('mec').innerHTML = "Mechanics"
    document.getElementById('logros').innerHTML = "ACHIEVEMENTS"
    document.getElementById('l1').innerHTML = "Web application development for entrepreneurship management"
    document.getElementById('l2').innerHTML = "Design and construction of environmental and energy monitoring equipment"
    document.getElementById('l3').innerHTML = "Design and construction of industrial automation systems"
    document.getElementById('l4').innerHTML = "Work team management (6 people)"
    document.getElementById('l5').innerHTML = "Repair of highly complex equipment"
    document.getElementById('exp').innerHTML = "EXPERIENCE"
    document.getElementById('e1').innerHTML = "2022 - Freelance Developer"
    document.getElementById('e2').innerHTML = "2020/2022 - Nativa S.R.L., medical equipment and supplies"
    document.getElementById('e3').innerHTML = "Position: In charge of Technical Service and After Sales"
    document.getElementById('e4').innerHTML = "Tasks: Area management and work team"
    document.getElementById('e5').innerHTML = "2020/2022 - Nativa S.R.L., medical equipment and supplies"
    document.getElementById('e6').innerHTML = "Position: Specialist technician"
    document.getElementById('e7').innerHTML = "Tasks: Repair of medical equipment, development of maintenance protocols, preparation of budgets, training"
    document.getElementById('e8').innerHTML = "2013/2017 - UTN Environmental Chemical Research Center"
    document.getElementById('e9').innerHTML = "Position: Electronic Technician."
    document.getElementById('e10').innerHTML = "Tasks: Development, repair and maintenance of environmental measurement equipment"
    document.getElementById('est').innerHTML = "EDUCATION"
    document.getElementById('f1').innerHTML = "2009/incomplete - ELECTRONIC ENGINEERING - National Technological University Regional Faculty of Córdoba, completed up to 5th full year."
    document.getElementById('f2').innerHTML = "2008 - TECHNICAL BACHELOR IN ELECTRONIC MAINTENANCE - Provincial High School Institute No. 266 General Savio (Rio Tercero, Córdoba)"
    document.getElementById('cursos').innerHTML = "Courses and training"
    document.getElementById('c1').innerHTML = "2023/Current - Full course on Machine Learning: Data Science in Python -Udemy - Instructor Juan Gabriel Gomila"
    document.getElementById('c2').innerHTML = "2023/Cursing - First steps in front end development - TICMAS, Academy"
    document.getElementById('c3').innerHTML = "2022 - Scrum Master and Product Owner Certification Year 2022 - Udemy - Instructor Alvaro Chirou"
    document.getElementById('c4').innerHTML = "2022 - OPTICAL REMOTE SENSING COURSE INTRODUCTORY LEVEL - CONAE - Duration 30 hours"
    document.getElementById('c5').innerHTML = "2022 - GIT + GitHub - Udemy - Instructor Fernando Herra"
    document.getElementById('c6').innerHTML = "2022 - DATA ANALYTICS COURSE - ICARO, UNC - Duration 40 hours"
    document.getElementById('c7').innerHTML = "2021 - PYTHON 3 MASTER COURSE - Udemy - Instructor Héctor Costa Guzmán"
    document.getElementById('c8').innerHTML = "2011 - PIC MICROCONTROLLERS COURSE. - National Technological University - Regional Faculty of Córdoba"
    document.getElementById('c9').innerHTML = "2011 - PROFESSIONAL TRAINING COURSE IN ASSEMBLY, REPAIR AND - PC MAINTENANCE. - C.UNIX Computer Consultant"
    document.getElementById('edad_1').innerHTML = "31 years old"
    document.getElementById('idiomas').innerHTML = "English, inter level"
    document.getElementById('des_1').innerHTML = "Download CV"
    

}

document.getElementById('ing_2').onclick = function(){
    document.getElementById('sub_2').innerHTML = "Software Developer"
    document.getElementById('skills').innerHTML = "SKILLS"
    document.getElementById('prog').innerHTML = "Software"
    document.getElementById('agile').innerHTML = "Agile - SCRUM"
    document.getElementById('elec').innerHTML = "Electronics"
    document.getElementById('comp').innerHTML = "Computing"
    document.getElementById('mec').innerHTML = "Mechanics"
    document.getElementById('logros').innerHTML = "ACHIEVEMENTS"
    document.getElementById('l1').innerHTML = "Web application development for entrepreneurship management"
    document.getElementById('l2').innerHTML = "Design and construction of environmental and energy monitoring equipment"
    document.getElementById('l3').innerHTML = "Design and construction of industrial automation systems"
    document.getElementById('l4').innerHTML = "Work team management (6 people)"
    document.getElementById('l5').innerHTML = "Repair of highly complex equipment"
    document.getElementById('exp').innerHTML = "EXPERIENCE"
    document.getElementById('e1').innerHTML = "2022 - Freelance Developer"
    document.getElementById('e2').innerHTML = "2020/2022 - Nativa S.R.L., medical equipment and supplies"
    document.getElementById('e3').innerHTML = "Position: In charge of Technical Service and After Sales"
    document.getElementById('e4').innerHTML = "Tasks: Area management and work team"
    document.getElementById('e5').innerHTML = "2020/2022 - Nativa S.R.L., medical equipment and supplies"
    document.getElementById('e6').innerHTML = "Position: Specialist technician"
    document.getElementById('e7').innerHTML = "Tasks: Repair of medical equipment, development of maintenance protocols, preparation of budgets, training"
    document.getElementById('e8').innerHTML = "2013/2017 - UTN Environmental Chemical Research Center"
    document.getElementById('e9').innerHTML = "Position: Electronic Technician."
    document.getElementById('e10').innerHTML = "Tasks: Development, repair and maintenance of environmental measurement equipment"
    document.getElementById('est').innerHTML = "EDUCATION"
    document.getElementById('f1').innerHTML = "2009/incomplete - ELECTRONIC ENGINEERING - National Technological University Regional Faculty of Córdoba, completed up to 5th full year."
    document.getElementById('f2').innerHTML = "2008 - TECHNICAL BACHELOR IN ELECTRONIC MAINTENANCE - Provincial High School Institute No. 266 General Savio (Rio Tercero, Córdoba)"
    document.getElementById('cursos').innerHTML = "Courses and training"
    document.getElementById('c1').innerHTML = "2023/Current - Full course on Machine Learning: Data Science in Python -Udemy - Instructor Juan Gabriel Gomila"
    document.getElementById('c2').innerHTML = "2023/Cursing - First steps in front end development - TICMAS, Academy"
    document.getElementById('c3').innerHTML = "2022 - Scrum Master and Product Owner Certification Year 2022 - Udemy - Instructor Alvaro Chirou"
    document.getElementById('c4').innerHTML = "2022 - OPTICAL REMOTE SENSING COURSE INTRODUCTORY LEVEL - CONAE - Duration 30 hours"
    document.getElementById('c5').innerHTML = "2022 - GIT + GitHub - Udemy - Instructor Fernando Herra"
    document.getElementById('c6').innerHTML = "2022 - DATA ANALYTICS COURSE - ICARO, UNC - Duration 40 hours"
    document.getElementById('c7').innerHTML = "2021 - PYTHON 3 MASTER COURSE - Udemy - Instructor Héctor Costa Guzmán"
    document.getElementById('c8').innerHTML = "2011 - PIC MICROCONTROLLERS COURSE. - National Technological University - Regional Faculty of Córdoba"
    document.getElementById('c9').innerHTML = "2011 - PROFESSIONAL TRAINING COURSE IN ASSEMBLY, REPAIR AND - PC MAINTENANCE. - C.UNIX Computer Consultant"
    document.getElementById('edad_2').innerHTML = "31 years old"
    document.getElementById('des_2').innerHTML = "Download CV"
}

document.getElementById('esp_1').addEventListener('click', function(){
    location.reload()
});

document.getElementById('esp_2').addEventListener('click', function(){
    location.reload()
});
